// Generated by CoffeeScript 1.7.1
(function() {
  window.tic_sli = {
    slide: function(option) {
      var $body, $doc, $win, ani_style, constructor, doc_hei, op, win_hei, _ref;
      constructor = {
        x: "center",
        et: "ease-out",
        d: "1s"
      };
      op = $.extend(constructor, option);
      $doc = $(document);
      $win = $(window);
      $body = $('body');
      ani_style = "background-position " + op.d + " " + op.et;
      $body.css({
        'transition': ani_style,
        'moz-transition': ani_style,
        '-webkit-transition': ani_style,
        '-o-transition': ani_style,
        '-ms-transition': ani_style
      });
      _ref = [$doc.height(), $win.height()], doc_hei = _ref[0], win_hei = _ref[1];
      $win.on('resize', function(event) {
        return win_hei = $(this).height();
      });
      return $win.on('scroll', function(event) {
        var img_scroll, scroll_hei;
        doc_hei = doc_hei === $doc.height() ? doc_hei : $doc.height();
        scroll_hei = $doc.scrollTop();
        img_scroll = scroll_hei / (doc_hei - win_hei) * 100..toFixed(7);
        return $body.css("background-position", op.x + (" " + img_scroll + "%"));
      });
    },
    ticker: function(option) {
      var $body, constructor, op;
      constructor = {
        url: "",
        d: []
      };
      op = $.extend(constructor, option);
      $body = $('body');
      return $.ajax({
        url: op.url,
        data: {},
        success: function(value) {
          var day, moment, now, this_moment, _i, _len;
          if (typeof value === "string") {
            value = $.parseJSON(value);
          }
          day = value.backgrounds;
          now = new Date().getHours();
          for (_i = 0, _len = day.length; _i < _len; _i++) {
            moment = day[_i];
            if ((parseInt(moment.started) <= now && now <= parseInt(moment.ended))) {
              this_moment = moment;
            }
          }
          if (this_moment) {
            if (this_moment.image) {
              $body.css("background-image", "url(" + this_moment.image + ")");
            } else if (op.d[0]) {
              $body.css("background-image", "url(" + op.d[0] + ")");
            }
            if (this_moment.color) {
              return $body.css("background-color", this_moment.color);
            } else if (op.d[1]) {
              return $body.css("background-color", op.d[1]);
            }
          } else {
            if (op.d[0]) {
              $body.css("background-image", "url(" + op.d[0] + ")");
            }
            if (op.d[1]) {
              return $body.css("background-color", op.d[1]);
            }
          }
        },
        error: function() {
          if (op.d[0]) {
            $body.css("background-image", "url(" + op.d[0] + ")");
          }
          if (op.d[1]) {
            return $body.css("background-color", op.d[1]);
          }
        }
      });
    }
  };

}).call(this);
